### ISSUE TITLE
Create templates Issue

### ISSUE THREAD

**Issue by mbustamanted** [renderpci/dedalo#38]
In the version of Dédalo 5.7.77 03-07-2021, with DB PGSQL 11.9 we detected an error that makes the option to create print templates disappear when printing. The log shows nothing significant. User permissions to create templates have been reviewed and are correct.
![Captura](https://user-images.githubusercontent.com/78954983/111454550-0998bd80-8715-11eb-9e07-181254524757.PNG)
![Captura2](https://user-images.githubusercontent.com/78954983/111454682-3351e480-8715-11eb-9b09-1e39c838b1f7.PNG)

**Comment by renderpci** [comment]
Hi @mbustamanted!

This issue is fixed in the v5.8.0. this version change the data model into «matrix_activity» and it can take some time to update it. And you will need update the ontology the the newer version before run the update script into the tool administration.

You can download this version and update [Dédalo. v.5.8.0](https://github.com/renderpci/dedalo/releases/tag/V5.8.0)

Thanks!

**Comment by JJAM2019** [comment]
Dear All,

We still experience some issues with the print templates: 
When we try to print, Dedalo returns one error “**Sorry. Error was found on render pdf file. See the log for more info** “. 

You can found the log and the capture of the error screen attached to this ticket.

[Error plantillas impresion Dedalo.txt](https://github.com/renderpci/dedalo/files/6491798/Error.plantillas.impresion.Dedalo.txt)
![print_error](https://user-images.githubusercontent.com/16013864/118445800-2fc7e300-b6ef-11eb-91ee-354cbf907af6.png)


Also, we can’t delete any template. There isn’t any button or command to do it.

Thanks a lot for your time. Regards.

**Comment by renderpci** [comment]
Dear JJAN2019

I re-open this issue.

I see that the problem is a network error:

` Error: Failed loading page http://prepatrimonioinmaterial.admon-cfnavarra.es/dedalo/media/print/ich1/-1/1_ich1_1.html `

Seems like the server can do the call to himself, maybe you can try to do the terminal command:

` /usr/local/bin/wkhtmltopdf -L 10 -R 10 -T 10 -B 20 -q --footer-html 'http://prepatrimonioinmaterial.admon-cfnavarra.es/dedalo/media/print/ich1/-1/footer.html' `

or maybe you can try with wget command (it's a simple command)

`wget http://prepatrimonioinmaterial.admon-cfnavarra.es/dedalo/media/print/ich1/-1/footer.html `

I hope that you can find the problem.

Best
